version: 2
jobs:     
   node8:
     docker:
       - image: circleci/node:8.8     
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-dep-8-{{ checksum "package-lock.json" }}
       - run: npm install
       - save_cache:
           key: npm-dep-8-{{ checksum "package-lock.json" }}
           paths:
             - node_modules/
       - run: npm run test
       
   node10:
     docker:
       - image: circleci/node:10  
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-dep-10-{{ checksum "package-lock.json" }}
       - run: npm install
       - save_cache:
           key: npm-dep-10-{{ checksum "package-lock.json" }}
           paths:
             - node_modules/
       - run: npm run test
       
   node12:
     docker:
       - image: circleci/node:12.9  
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-dep-12-{{ checksum "package-lock.json" }}
       - run: npm install
       - save_cache:
           key: npm-dep-12-{{ checksum "package-lock.json" }}
           paths:
             - node_modules/
       - run: npm run test
       - run: npm run coverage
       
workflows:
  version: 2
  node8_node10_node_12:
    jobs:
      - node8
      - node10
      - node12
