version: 2
jobs:
   node6:
     docker:
       - image: circleci/node:6.10     
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-dep-{{ checksum "package-lock.json" }}
       - run: npm install
       - save_cache:
           key: npm-dep-{{ checksum "package-lock.json" }}
           paths:
             - node_modules/
       - run: npm run test
       - run: npm run coverage
       
   node8:
     docker:
       - image: circleci/node:8.8     
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-dep-{{ checksum "package-lock.json" }}
       - run: npm install
       - save_cache:
           key: npm-dep-{{ checksum "package-lock.json" }}
           paths:
             - node_modules/
       - run: npm run test
       - run: npm run coverage
       
   node10:
     docker:
       - image: circleci/node:10  
     steps:
       - checkout
       - restore_cache:
           keys:
             - npm-dep-{{ checksum "package-lock.json" }}
       - run: npm install
       - save_cache:
           key: npm-dep-{{ checksum "package-lock.json" }}
           paths:
             - node_modules/
       - run: npm run test
       - run: npm run coverage
       
workflows:
  version: 2
  node6_node8_node10:
    jobs:
      - node6
      - node8
      - node10
